# ============================================================================
# Promptometer Core — TaskAssessor.assess() test suite (zero-dep)
# Ejecutar: `python packages/core/test_assess.py` o `pytest packages/core`
# fixtures/assess-cases.json es la especificación compartida con el port JS.
# ============================================================================

import builtins
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import promptometer_core as pc  # noqa: E402

FIXTURES = os.path.join(HERE, "fixtures", "assess-cases.json")


def _load_cases():
    with open(FIXTURES, encoding="utf-8") as fh:
        return json.load(fh)["cases"]


def _check_case(case):
    r = pc.assess(case["prompt"], case["context"])
    exp = case["expect"]
    got = {
        "score": r["score"],
        "quality": r["quality"],
        "intent": r["intent"],
        "exploration_risk": r["exploration_risk"],
        "suggest_split": r["scope"]["suggest_split"],
        "recommended_tier": r["recommended_tier"],
        "steering": r["steering"],
        "correction": r["correction"],
        "issue_ids": [i["id"] for i in r["issues"]],
        "targets": r["targets"],
        "has_scaffold": bool(r["scaffold"]),
    }
    diffs = {k: (exp[k], got[k]) for k in exp if exp[k] != got[k]}
    assert not diffs, "{}: {}".format(case["name"], diffs)


def test_fixtures():
    for case in _load_cases():
        _check_case(case)


def test_result_shape_is_complete_and_json_safe():
    for prompt in ("", None, 42, "a", "agrega tests unitarios para yunta/intent.py"):
        r = pc.assess(prompt)
        for key in ("score", "quality", "intent", "targets", "grounded", "exploration_risk",
                    "explorationRisk", "scope", "recommended_tier", "recommendedTier",
                    "steering", "correction", "signals", "issues", "tip", "scaffold"):
            assert key in r, key
        assert isinstance(r["tip"], str) and len(r["tip"]) > 10
        dump = json.dumps(r)
        assert "NaN" not in dump


def test_single_tip_prioritizes_highest_severity():
    r = pc.assess("edita auth/inexistente.py para validar el token",
                  {"known_files": ["js/app.js"]})
    assert r["tip"] == r["issues"][0]["message"]
    assert "auth/inexistente.py" in r["tip"]


def test_lang_en_messages():
    r = pc.assess("arreglalo", {"lang": "en"})
    assert r["tip"].startswith("Avoid ambiguous")
    assert r["scaffold"].startswith("In ")


def test_assess_does_no_io():
    real_open = builtins.open
    real_listdir = os.listdir
    real_run = subprocess.run

    def boom(*a, **k):
        raise AssertionError("assess() no debe hacer I/O")

    cases = _load_cases()
    builtins.open, os.listdir, subprocess.run = boom, boom, boom
    try:
        for case in cases:
            pc.assess(case["prompt"], case["context"])
    finally:
        builtins.open, os.listdir, subprocess.run = real_open, real_listdir, real_run


# ── Paridad JS: las regex, keywords y mensajes viven en Python; el port JS los
#    embebe como TA_SPEC entre marcadores. `python test_assess.py --sync-js` lo regenera.
JS_CORE = os.path.join(HERE, "promptometer-core.js")
SPEC_START, SPEC_END = "/* <ta-spec> generated by test_assess.py --sync-js; do not edit */", "/* </ta-spec> */"


def build_js_spec():
    import re
    patterns = {}
    for name, val in sorted(vars(pc).items()):
        if name.startswith("_RE_TA_") and isinstance(val, re.Pattern):
            patterns[name[len("_RE_TA_"):]] = {
                "source": val.pattern,
                "flags": "i" if val.flags & re.IGNORECASE else "",
            }
    return {
        "patterns": patterns,
        "softwareKeywords": pc._TA_SOFTWARE_KEYWORDS,
        "researchKeywords": pc._TA_RESEARCH_KEYWORDS,
        "deepKeywords": pc._TA_DEEP_KEYWORDS,
        "fastKeywords": pc._TA_FAST_KEYWORDS,
        "moduleStoplist": sorted(pc._TA_MODULE_STOPLIST),
        "severityRank": pc._TA_SEVERITY_RANK,
        "messages": pc._TA_MESSAGES,
    }


def _render_spec_block():
    body = json.dumps(build_js_spec(), ensure_ascii=False, indent=2)
    body = "\n".join("  " + line for line in body.splitlines()).lstrip()
    return "{}\n  const TA_SPEC = {};\n  {}".format(SPEC_START, body, SPEC_END)


def _split_js():
    with open(JS_CORE, encoding="utf-8") as fh:
        src = fh.read()
    i, j = src.index(SPEC_START), src.index(SPEC_END) + len(SPEC_END)
    return src, i, j


def sync_js():
    src, i, j = _split_js()
    with open(JS_CORE, "w", encoding="utf-8", newline="") as fh:
        fh.write(src[:i] + _render_spec_block() + src[j:])


def test_js_spec_in_sync():
    src, i, j = _split_js()
    # Normaliza CRLF (checkout en Windows con autocrlf) antes de comparar
    assert src[i:j].replace("\r\n", "\n") == _render_spec_block(), "TA_SPEC desincronizado: corre `python test_assess.py --sync-js`"


def _parity_jobs():
    """Fixtures + corpus aleatorio determinista (acentos, unicode, voz, rutas) para cazar
    diferencias entre `re` de Python y RegExp de JS."""
    import random
    rnd = random.Random(7)
    parts = ["únicamente", "añade", "Añade", "código", "está mal", "así no", "reviértelo", "función",
             "`get_user()`", "src/auth.py", "auth.py", "yunta barra intent punto py", "clase Foo", "CamelCase",
             "snake_case_var", "KeyError", "sin romper tests", "en viñetas", "cátedra", "audio", "tabla",
             "causa raíz", "rápido", "explica", "no,", "esperaba 404", "js/app.js", "analyzer", "naïve",
             "日本語", "🤖", "Привет", "e.g.", "v1.0", "y/o", "http://x.com/a", "ñandú", "über_func()",
             "deshaz", "continúa", "dale", "arreglalo", "crea", "nuevo", "README.md", "punto js"]
    known = ["js/analyzer.js", "js/app.js", "server.js", "src/auth.py", "über/ñandú.py", "README.md"]
    ctxs = [{}, {"turn": 2}, {"known_files": known}, {"known_files": known, "turn": 3, "lang": "en"},
            {"is_voice": True}]
    jobs = [(c["prompt"], c["context"]) for c in _load_cases()]
    for _ in range(300):
        text = " ".join(rnd.choice(parts) for _ in range(rnd.randint(1, 9)))
        jobs.append((text, rnd.choice(ctxs)))
    return jobs


def test_js_parity():
    """Si hay node disponible, el port JS debe producir exactamente lo mismo que Python."""
    import shutil
    import tempfile
    node = shutil.which("node")
    if not node:
        return
    jobs = _parity_jobs()
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False, encoding="utf-8") as fh:
        json.dump(jobs, fh, ensure_ascii=False)
    try:
        script = (
            "const pc=require(process.argv[1]);const jobs=JSON.parse(require('fs').readFileSync(process.argv[2],'utf8'));"
            "process.stdout.write(JSON.stringify(jobs.map(([t,c])=>pc.assess(t,c))));"
        )
        out = subprocess.run([node, "-e", script, JS_CORE, fh.name], capture_output=True, text=True,
                             encoding="utf-8", check=True)
    finally:
        os.unlink(fh.name)
    for (text, ctx), js in zip(jobs, json.loads(out.stdout)):
        py = pc.assess(text, ctx)
        diffs = {k: (py[k], js.get(k)) for k in py if py[k] != js.get(k)}
        assert not diffs, "{!r} {}: py vs js {}".format(text[:60], ctx, diffs)


def _cli(*args):
    env = dict(os.environ, PYTHONIOENCODING="utf-8")
    out = subprocess.run([sys.executable, os.path.join(HERE, "promptometer_core.py")] + list(args),
                         capture_output=True, text=True, encoding="utf-8", env=env, check=True)
    return json.loads(out.stdout)


def test_cli_assess_json():
    r = _cli("assess", "reviértelo, te equivocaste", "--turn", "2")
    assert r["correction"] is True and r["turn"] == 2


def test_cli_files_from_git():
    r = _cli("assess", "edita auth/inexistente.py", "--files-from", "git", "--compact")
    assert r["grounded"] is True
    assert r["targets"]["missing"] == ["auth/inexistente.py"]


if __name__ == "__main__":
    if "--sync-js" in sys.argv:
        sync_js()
        print("TA_SPEC regenerado en promptometer-core.js")
        sys.exit(0)
    tests = [(n, f) for n, f in sorted(globals().items()) if n.startswith("test_") and callable(f)]
    failed = 0
    for name, fn in tests:
        try:
            fn()
            print(" PASS  " + name)
        except Exception as e:  # noqa: BLE001
            failed += 1
            print(" FAIL  {}: {}".format(name, e))
    print("\n{}/{} PASS".format(len(tests) - failed, len(tests)))
    sys.exit(1 if failed else 0)
